### ISSUE TITLE
Primary Key from int to long?

### ISSUE THREAD

**Issue by maldworth** [skoruba/AuditLogging#2]
Perhaps the intent is for the user to purge the logs every so often, but I usually like making my Primary Id's longs these days (BIGINT in SqlServer).

https://github.com/skoruba/AuditLogging/blob/f7c627efceb26eff75919dc5975fa1d20286ee32/src/Skoruba.AuditLogging.EntityFramework/Entities/AuditLog.cs#L10

Do you think this might be worth it? If not, then just close this issue.

**Comment by skoruba** [comment]
Good catch! For sure, I will update to long.
If you want - you can send a PR. 👍

**Comment by skoruba** [comment]
Done in beta6 package.

Thanks!
